controllers/UserController.php
<?php

namespace app\controllers;

use Yii;
use app\models\User;
use app\models\Video;
use app\models\Favorite;
use app\models\Comment;
use app\models\Visit;
use app\models\UserSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\models\LoginForm;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all User models.
     * Only available to logged in admin user.
     * @return mixed
     */
    public function actionIndex()
    {
        if (Yii::$app->user->getIsGuest()) {
            //not logged in
            return $this->redirect(['user/login']);
        }

        if (!Yii::$app->user->identity->isAdmin()) {
            // is admin
            return $this->redirect(['video/index']);
        }

        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single User model and video models related to it. Along with video models, all visits and users models are passed into view.
     * Only available to logged in users.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        if (Yii::$app->user->getIsGuest()) {
            //not logged in
            return $this->redirect(['user/login']);
        }

        $videomodel = new Video();
        $videos = $videomodel->find()->where(['user_id' => $id])->all();

        // visits
        $visitmodel = new Visit();
        $visits = $visitmodel->find()->all();

        // users
        $usermodel = new User();
        $users = $usermodel->find()->all();

        return $this->render('view', [
            'model' => $this->findModel($id),
            'videos' => $videos,
            'users' => $users,
            'visits' => $visits,
        ]);
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page of user.
     * Only available to the logged in user of this model.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        if (Yii::$app->user->getIsGuest()) {
            //not logged in
            return $this->redirect(['user/login']);
        }

        $model = $this->findModel($id);

        if (Yii::$app->user->identity->id != $model->user_id) {
            // is admin
            return $this->redirect(['index']);
        }

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the login page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        if (Yii::$app->user->getIsGuest()) {
            //not logged in
            return $this->redirect(['user/login']);
        }

        $model = $this->findModel($id);

        if (Yii::$app->user->identity->id != $model->user_id) {
            // is admin
            return $this->redirect(['index']);
        }

        // remove favorites
        $favoritemodel = new Favorite();
        $favorites = $favoritemodel->find()->where(['user_id' => $id])->all();
        foreach($favorites as $favorite) {
            $favorite->delete();
        }

        // remove favorites
        $commentmodel = new Comment();
        $comments = $commentmodel->find()->where(['user_id' => $id])->all();
        foreach($comments as $comment) {
            $comment->delete();
        }

        // remove favorites
        $videomodel = new Video();
        $videos = $videomodel->find()->where(['user_id' => $id])->all();
        foreach($videos as $video) {
            $videofavorites = $favoritemodel->find()->where(['user_id' => $id])->all();
            $videocomments = $commentmodel->find()->where(['user_id' => $id])->all();
            foreach($videocomments as $comment) {
                $comment->delete();
            }
            foreach($videofavorites as $comment) {
                $comment->delete();
            }
            $video->delete();
        }

        $model->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    /**
     * Displays register page.
     * If user is logged in, page is redirected to "video/index" page.
     * @return string
     */
    public function actionRegister()
    {
        $user = new User();

        if (!Yii::$app->user->getIsGuest()) {
            //not logged in
            return $this->redirect(['video/index']);
        }

        if ($user->load(Yii::$app->request->post()) && $user->register($user->load(Yii::$app->request->post()))) {

//            \Yii::$app->mailer->compose('/mail/registration', ['user' => $user])
//                ->setFrom(['noreply@olv.example' => 'Registration'])
//                ->setTo($user->username)
//                ->setSubject('Registration | OLV')
//                ->send();

            return $this->goBack();
        } else {
            return $this->render('register', [
                'user' => $user,
            ]);
        }
    }

    /**
     * Displays Login page.
     * If user is logged in, page is redirected to "video/index" page.
     * @return string
     */
    public function actionLogin()
    {
        $login = new LoginForm();

        if (!Yii::$app->user->getIsGuest()) {
            //not logged in
            return $this->redirect(['video/index']);
        }

        if ($login->load(Yii::$app->request->post()) && $login->login()) {
            $session= Yii::$app->session;
            $session->open();
            return $this->goBack();
        }

        return $this->render('login', [
            'login' => $login,
        ]);
    }

    /**
     * Logout action.
     * Page is redirected to landing login.
     * @return string
     */
    public function actionLogout()
    {
        if (Yii::$app->user->getIsGuest()) {
            //not logged in
            return $this->redirect(['user/login']);
        }

        $session = Yii::$app->session;
        $session->destroy();
        Yii::$app->user->logout();
        return $this->redirect(['user/login']);
    }
}

views/snippets/dashboard.php
<ul class="dashboard">
    <li class="dashboard__item dashboard__item--red">
        <a href="/video/my">
            <h2><?= $dashboard->videos ?> <small>videos created</small></h2>
        </a>
    </li>
    <li class="dashboard__item dashboard__item--blue">
        <h2><?= $dashboard->comments ?> <small>comments written</small></h2>
    </li>
    <li class="dashboard__item dashboard__item--green">
        <a href="/video/favorites">
            <h2><?= $dashboard->favorited ?> <small>favorited videos</small></h2>
        </a>
    </li>
    <li class="dashboard__item dashboard__item--orange">
        <h2><?= $dashboard->rated ?> <small>videos rated</small></h2>
    </li>
</ul>
<div class="dashboard-labels">
    <a class="labels labels__blue" href="/video/label/math">Math</a>
    <a class="labels labels__orange" href="/video/label/biology">Biology</a>
    <a class="labels labels__red" href="/video/label/it">IT</a>
    <a class="labels labels__green" href="/video/label/history">History</a>
    <a class="labels labels__blue" href="/video/label/database">Database</a>
    <a class="labels labels__green" href="/video/label/literature">Literature</a>
    <a class="labels labels__orange" href="/video/label/physics">Physics</a>
    <a class="labels labels__red" href="/video/label/music">Music</a>
    <a class="labels labels__green" href="/video/label/sports">Sports</a>
    <a class="labels labels__blue" href="/video/label/other">Other</a>
</div>

views/snippets/footer.php
<footer class="footer">
    <div class="footer__inner">
        <div class="footer__left">Online Learning Video Repository</div>
        <div class="footer__right">Author: Georgy Marchuk</div>
    </div>
</footer>

views/snippets/header.php
<header class="header">
    <div class="header__holder">
        <a href="/" class="header__logo"><img src="/assets/custom/img/logo-olv.svg" alt="OLV"/></a>
        <div class="burger">
            <span></span>
        </div>
        <?php if(Yii::$app->user->isGuest): ?>
            <a href="/user/login" class="header__login">Login</a>
            <a href="/user/register" class="header__login">Register</a>
        <?php else: ?>
            <a href="/user/logout" class="header__login">Logout (<?= Yii::$app->user->identity->firstname ?>) <span class="icon icon-logout icon--right"></span></a>
            <a href="/video/create" class="header__add btn btn--blue btn--small">Add Video<span class="icon icon-plus icon--right"></span></a>
            <span  data-search class="header__add btn btn--green btn--small">Search<span class="icon icon-magnifying-glass icon--right"></span></span>
            <nav class="nav">
                <ul>
                    <li><a href="/video/my">My videos</a></li>
                    <li><a href="/video/favorites">Favorite</a></li>
                    <li><a href="/user/<?= Yii::$app->user->identity->id ?>">Profile</a></li>
                    <?php if(Yii::$app->user->identity->isAdmin()): ?>
                        <li><a href="/user">Users</a></li>
                    <?php endif ?>
                </ul>
            </nav>
        <?php endif ?>
    </div>
</header>

<nav class="nav nav-mobile">
    <div class="nav-mobile__holder">
        <ul>
            <?php if(Yii::$app->user->isGuest): ?>
                <li><a href="/user/login">Login</a></li>
                <li><a href="/user/register">Register</a></li>
            <?php else: ?>
                <?php if(Yii::$app->user->identity->isAdmin()): ?>
                    <li><a href="/user">Users</a></li>
                <?php endif ?>
                <li><a href="/user/<?= Yii::$app->user->identity->id ?>">Profile</a></li>
                <li><a href="/video/my">My videos</a></li>
                <li><a href="/video/favorites">Favorite</a></li>
                <li><a href="/user/logout">Logout (<?= Yii::$app->user->identity->firstname ?>) <span class="icon icon-logout icon--right"></span></a></li>
            <?php endif ?>
        </ul>
    </div>
</nav>

views/snippets/list-videos.php
<?php if(count($videos) != 0): ?>
    <ul class="list-videos">
        <?php foreach($videos as $video): ?>
            <?php
                // user of video
                foreach ($users as $user) {
                    if ($user->user_id == $video->user_id) {
                        $video_user = $user;
                        break;
                    }
                }
            ?>

            <?php
                // visits of video
                $video_visits = 0;
                foreach ($visits as $visit) {
                    if ($visit->video_id == $video->id) {
                        $video_visits++;
                    }
                }
            ?>
            <li>
                <a href="/video/<?= $video->id ?>">
                    <div class="list-videos__img">
                            <?php
                                $siteName = $urlQuery = explode(".", str_replace("www.", "", $urlParts = parse_url($video->url)['host']));
                                $siteName = array_slice($siteName, 0, -1);
                                $siteName = ucfirst(implode($siteName));
                                echo '<div class="list-videos__type">'.$siteName.'</div>';
                                if ($video->img !== null && $video->img !== '') {
                                    echo '<img src="' . $video->img .'" al>';
                                }
                            ?>
                    </div>
                    <p class="list-videos__url"><?= $video->url ?></p>
                    <h2><?= $video->title ?></h2>
                    <p class="list-videos__desc"><?= substr($video->description,0,120) ?>...</p>
                    <div class="list-videos__module">
                        <?php
                        $labels = explode(',', $video->labels);
                        $colors = ['blue', 'orange', 'red', 'green', 'purple'];

                        foreach($labels as $label) {
                            echo '<span class="labels labels__'.$colors[rand(0, 4)].'" style="opacity:'.(rand(8, 10)/10).'">'.$label.'</span>';
                        }
                        ?>
                    </div>
                    <div class="list-videos__user"><?= $video_user->getName(); ?></div>
                    <div class="list-videos__date"><?= \Yii::$app->formatter->asDatetime($video->date, "php:d/m/Y") ?></div>
                    <div class="list-videos__visits"><?= $video_visits ?> views</div>
                </a>
                <?php if(Yii::$app->user->identity->isAdmin() || Yii::$app->user->identity->id == $video->user_id): ?>
                    <div class="list-videos__admin">
                        <a href="/video/update/<?= $video->id ?>" class="btn btn--small btn--orange"><span class="icon icon-listing-option icon--left"></span>Edit</a>
                        <a href="/video/delete/<?= $video->id ?>" class="btn btn--small btn--red"><span class="icon icon-trash icon--left"></span>Delete</a>
                    </div>
                <?php endif ?>
            </li>
        <?php endforeach ?>
    </ul>
<?php else: ?>
    <h2 class="no-video">No videos available</h2>
<?php endif ?>

views/snippets/search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Comment */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="form search">
    <?php $form = ActiveForm::begin([
        'action' => ['video/search'],
        'method' => 'get',
    ]); ?>
    <div class="search__inner">
        <div class="form-group">
            <label class="control-label" for="search">Search</label>
            <input type="text" class="form-control" name="query" id="search" value="<?php if (isset($_GET['query'])) echo $_GET['query']; ?>"/>
            <?= Html::submitButton('Search', ['class' => 'btn btn--small btn--blue']) ?>
        </div>
    </div>
    <?php $form = ActiveForm::end(); ?>
</div>